USE q1u9gnricx1xg22v;

INSERT INTO Tags (name,  createdAt, updatedAt) VALUES
("Action", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
("Arcade", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
("Shooter", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
("Role Playing", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);